name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Versionning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.5.4
      - name: GitVersion Setup
        uses: gittools/actions/gitversion/setup@v2.0.1
        with:
          prefix: module2-
          log-path: module2/
          versionSpec: '6.x'

      - name: GitVersion Determine Version
        uses: gittools/actions/gitversion/execute@v2.0.1
        with:
          updateAssemblyInfo: true
