name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Versionning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  

      - name: GitVersion Setup
        uses: gittools/actions/gitversion/setup@v2.0.1
        with:
          versionSpec: '6.x'

      - name: GitVersion Determine Version
        uses: gittools/actions/gitversion/execute@v2.0.1
        with:
          updateAssemblyInfo: true
